### ISSUE TITLE
base images off of fedora images

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/myfedora#78]
**Proposal**
I am proposing to base all the images off of the images directly from fedora's registry, without the middle man of Universal Blue.

The new image names will be `Silvara` (Silverblue) and `Kova` (Kinoite). There will also be `hypr` editions (with Hyprland) editions.

Call `previous`/`current` streams.

`-git`, `-daily` and `-weekly` are called frequencies

`-weekly` will only build weekly.

`-git` will build weekly and on git pushes.

`-daily` will build daily and on git pushes.

**Advantages**
The `ublue-os/main` repository has been known in the past for making breaking changes without warning, such as removing rpmfusion repositories.

It is good to cut out the middle man and just add/remove what I want without upstream ublue repos (bluefin, bazzite, etc.) doing stuff without me knowing. This will result in a more stable experience, because fedora will likely only have breaking changes on new releases.

This will make it easier to transition to a more long-term supported distribution such as [AlmaLinux](https://almalinux.org). This is because we already have most of the work done at this point and just need to port that over to the new base.

**Disadvantages**
We will likely need to go back to just having previous and current fedora versions, without stable. This is because stable seems hard to implement (especially the couple of weeks of delay between a new fedora release and a new stable release).

**Intermediary Plan**

The current images will still be available and building regularly in the [`legacy`](https://github.com/noahdotpy/myublue/tree/legacy) branch. The new images based off fedora directly will be in the default `main` branch.

**Tasks**
- [x] Move current (ublue) images to `legacy` branch
- [x] Add image files
- [x] fastfetch uses fedora logo (in style of bluefin's fastfetch logos)
- [x] #80
- [x] Enable auto-updating by default
- [x] Enable flatpak auto-updating by default
- [x] Update documentation to match new images
